name: "Create branch protection rule"
on: push

jobs:
  test: # Test action's functionality
    runs-on: ubuntu-latest
    steps:
    - name: Branch Guardian
      uses: infamous-riddles/branch-guardian@v1
      with: 
        PERSONAL-ACCESS-TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        BASE-BRANCH-PATTERN: '^master\/[a-zA-Z0-9]+$'
        REQUIRED-NUMBER-OF-REVIEWERS: 1
        DISMISS-STALE-PR-APPROVALS-ON-NEW-COMMITS: 'false'
        REQUIRE-LINEAR-HISTORY: 'false'
        ALLOW-FORCE-PUSHES: 'false'
        ALLOW-DELETIONS: 'false'
        INCLUDE-ADMINISTRATORS: 'false'
